[package]
name = "test_cloudflare_workers"
repository.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen-futures = "0.4.49"
