services:
  workspace:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace
    networks:
      - workspace
    restart: 'no'

networks:
  workspace:
    driver: bridge
